#!/bin/bash
a=$1
b=$2
c=$3
d=$4
e=$5
f=$6
g=$7
h=$8
i=$9
j=${10}
k=${11}
l=${12}
echo $a
echo $b
echo $c
echo $d
echo $e
echo $f
echo $g
echo $h
echo $i
echo $j
echo $k
echo $l
echo "your script name is $0"
echo "The number of arguments are $#"
echo "the arguments in the script are $@"

